apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-shards
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: shard-a
          - cluster: shard-b
  template:
    metadata:
      name: myapp-{{cluster}}
    spec:
      project: default
      source:
        repoURL: https://github.com/matheusrdelima/lab-shards
        targetRevision: main
        path: apps/myapp
      destination:
        name: '{{cluster}}'
        namespace: app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true